###############################################################
### ACCOUNTS ACCOUNTS ACCOUNTS ACCOUNTS ACCOUNTS ACCOUNTS AC###
###############################################################

### Account Creation

POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "testuser4", "password": "testuser4", "email": "testuser4@mail.com" }


### Account Login

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "testuser4", "password": "password!" }

### Account Auth Testing

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: token d75a58f9cf4c2a629dcc0255aea8267d8335d815

### Following check

GET http://127.0.0.1:8000/following
Content-Type: application/json
Authorization: token d75a58f9cf4c2a629dcc0255aea8267d8335d815

###############################################################
### POPS POPS POPS POPS POPS POPS POPS POPS POPS POPS POPS P###
###############################################################

### Single Pop Retrieval

GET http://127.0.0.1:8000/pops/1
Content-Type: application/json

### Anomymous Timeline Retrieval

GET http://127.0.0.1:8000/pops/timeline/anon/1/
Content-Type: application/json

### User Timeline Retrieval w/o Repops

GET http://127.0.0.1:8000/pops/timeline/user/1/
Content-Type: application/json
Authorization: token d75a58f9cf4c2a629dcc0255aea8267d8335d815

### User Timeline Retrieval w/ Repops

GET http://127.0.0.1:8000/pops/timeline/user_with_repop/2/
Content-Type: application/json
Authorization: token d75a58f9cf4c2a629dcc0255aea8267d8335d815


###############################################################
### INTERACTIONS INTERACTIONS INTERACTIONS INTERACTIONS INTE###
###############################################################

### Like Retrieval

GET http://127.0.0.1:8000/pops/interaction/like/1/
Content-Type: application/json
Authorization: token d75a58f9cf4c2a629dcc0255aea8267d8335d815

### Like Toggle

PUT http://127.0.0.1:8000/pops/interaction/like/1/
Content-Type: application/json
Authorization: token d75a58f9cf4c2a629dcc0255aea8267d8335d815

### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###

### Repop Retrieval

GET http://127.0.0.1:8000/pops/interaction/repop/1/
Content-Type: application/json
Authorization: token d75a58f9cf4c2a629dcc0255aea8267d8335d815

### Repop Toggle

PUT http://127.0.0.1:8000/pops/interaction/repop/1/
Content-Type: application/json
Authorization: token d75a58f9cf4c2a629dcc0255aea8267d8335d815

### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###

### Bookmark Retrieval - page

GET http://127.0.0.1:8000/pops/interaction/bookmark/1/
Content-Type: application/json
Authorization: token d75a58f9cf4c2a629dcc0255aea8267d8335d815