# Generated by Django 4.1.7 on 2023-11-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlikes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='poplikes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='poprepop',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='handle',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='CommentRepop',
        ),
    ]
