# Generated by Django 4.1.7 on 2023-12-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popfeed', '0003_alter_useraccount_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='handle',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
