# Generated by Django 4.1.7 on 2023-12-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popfeed', '0004_alter_useraccount_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlikes',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='commentlikes',
            name='user_id',
        ),
        migrations.AddField(
            model_name='popposts',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='popfeed.popposts'),
        ),
        migrations.DeleteModel(
            name='PopComments',
        ),
        migrations.DeleteModel(
            name='CommentLikes',
        ),
    ]
